### ISSUE TITLE
Must try Sinatra

### ISSUE THREAD

**Issue by xr09** [nebtrx/Ticketee#1]
Put this in
your pipe

```
$ gem install sinatra
$ ruby hi.rb
== Sinatra has taken the stage ...
>> Listening on 0.0.0.0:4567
```

and smoke it :grin:

**Comment by nebtrx** [comment]
easy cowboy, one step at a time, I have too much to process, to look under the hood....but I'll do it. Apparently Ruby loves DSLs.

**Comment by xr09** [comment]
Just be sure to give it try later: https://github.com/leah/tinytinyurl/blob/master/tinytiny.rb
